diceeyes/app.py
from flask import Flask

from diceeyes.blueprints.page import page


def create_app(settings_override=None):
    """
    Create a Flask application using the app factory pattern.

    :param settings_override: Override settings
    :return: Flask app
    """
    app = Flask(__name__, instance_relative_config=True)

    app.config.from_object('config.settings')
    app.config.from_pyfile('settings.py', silent=True)

    if settings_override:
        app.config.update(settings_override)

    app.register_blueprint(page)

    return app

diceeyes/blueprints/page/__init__.py
from diceeyes.blueprints.page.views import page

diceeyes/blueprints/page/views.py
from flask import Blueprint, render_template

page = Blueprint('page', __name__, template_folder='templates')


@page.route('/')
def home():
    return render_template('page/home.html')


@page.route('/terms')
def terms():
    return render_template('page/terms.html')


@page.route('/privacy')
def privacy():
    return render_template('page/privacy.html')

diceeyes/templates/layouts/_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="{% block meta_description %}{% endblock meta_description %}"
    />
    <title>Diceeyes - {% block title %} {% endblock title %}</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/vendor/bootstrap.min.css') }}"
    />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/vendor/all.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/main.css') }}"
    />
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
        <a
          href="{{ url_for('page.home') }}"
          class="navbar-brand d-flex align-items-center"
        >
          <img
            src="{{ url_for('static', filename='images/snake-eyes.jpg') }}"
            class="img-responsive"
            width="80%"
            height="50"
            title="Dice Eyes"
            alt="Dice Eyes"
          />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarsExample09"
          aria-controls="navbarsExample09"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample09">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#"
                >Home <span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link disabled"
                href="#"
                tabindex="-1"
                aria-disabled="true"
                >Disabled</a
              >
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="dropdown09"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
                >Dropdown</a
              >
              <div class="dropdown-menu" aria-labelledby="dropdown09">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
          </ul>
          <form class="form-inline my-2 my-md-0">
            <input
              class="form-control"
              type="text"
              placeholder="Search"
              aria-label="Search"
            />
          </form>
        </div>
      </nav>
    </div>
    <main class="container">
      <div class="md-margin-top">{% block heading %}{% endblock heading %}</div>
      {% block body %}{% endblock body %}
    </main>

    <footer class="footer my-2 pt-2 text-muted text-center text-small">
      <p class="mb-1">&copy; 2020 Dice Eyes</p>
      <ul class="list-inline">
        <li class="list-inline-item">
          <a href="{{ url_for('page.privacy') }}">Privacy</a>
        </li>
        <li class="list-inline-item">
          <a href="{{ url_for('page.terms') }}">Terms</a>
        </li>
        <li class="list-inline-item"><a href="#">Support</a></li>
      </ul>
    </footer>

    <script src="{{ url_for('static', filename='js/vendor/jquery.slim.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/bootstrap.min.js') }}"></script>
  </body>
</html>